server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://frumjfmcjiipwm:6edba1255e60c0636e5b4dbc649c814e5a8dcefb3102b8e7ade9305e6cd38a1e@ec2-18-214-195-34.compute-1.amazonaws.com:5432/dccualtvkblb9i

    username: frumjfmcjiipwm
    password: 6edba1255e60c0636e5b4dbc649c814e5a8dcefb3102b8e7ade9305e6cd38a1e
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp da Dio Com o Santander.
